<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '57e994ca5a9dfff5a5f33ac5e2003950',
  'DATABASE_URL' => 'mysql://root:root@127.0.0.1:3380/psd2?serverVersion=8.0&charset=utf8mb4',
);
